---
name: Feature Request / Enhancement
description: Suggest an iOS-specific improvement to GSD:iOS
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Is this iOS-specific? If the improvement applies to all GSD platforms,
        consider opening it at [gsd-build/get-shit-done](https://github.com/gsd-build/get-shit-done/issues).

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What iOS development problem does this solve?
    validations:
      required: true

  - type: textarea
    id: ios_context
    attributes:
      label: iOS context
      description: Which Apple frameworks, patterns, or Xcode features are involved?
      placeholder: "e.g., involves SwiftData migrations, WidgetKit, or StoreKit 2"
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
    validations:
      required: false
